"""record embedding model and chunk size on documents

Revision ID: 56ebd234259d
Revises: 0420d61f29dd
Create Date: 2026-09-15 12:13:57.953838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56ebd234259d'
down_revision: Union[str, Sequence[str], None] = '0420d61f29dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 注意：这三列是 NOT NULL，如果表里已经有数据，不加 server_default 会直接失败
    # （MySQL 报 "Invalid use of NULL value"）。自动生成的版本没有默认值，
    # 空库上能过、有数据的库上会炸，所以这里手工补上。
    # 已有记录的默认值表示「入库时还没记录这些信息」，用 0 / 空串表达，不要瞎填。
    op.add_column(
        "documents", sa.Column("chunk_size", sa.Integer(), nullable=False, server_default="0")
    )
    op.add_column(
        "documents",
        sa.Column("embedding_model", sa.String(length=64), nullable=False, server_default=""),
    )
    op.add_column(
        "documents", sa.Column("embedding_dim", sa.Integer(), nullable=False, server_default="0")
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'embedding_dim')
    op.drop_column('documents', 'embedding_model')
    op.drop_column('documents', 'chunk_size')
    # ### end Alembic commands ###
